<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HfTIs54' shared service.

return $this->privates['.service_locator.HfTIs54'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'session' => ['services', 'session', 'getSessionService.php', true],
    'visitorLog' => ['privates', 'App\\Model\\VisitorLog', 'getVisitorLogService.php', true],
], [
    'session' => '?',
    'visitorLog' => 'App\\Model\\VisitorLog',
]);
