<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._8tqfmn' shared service.

return $this->privates['.service_locator._8tqfmn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'databaseBackup' => ['privates', 'App\\Model\\DatabaseBackup\\DatabaseBackup', 'getDatabaseBackupService.php', true],
], [
    'databaseBackup' => 'App\\Model\\DatabaseBackup\\DatabaseBackup',
]);
