<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Model\DatabaseBackup\DatabaseBackup' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'DatabaseBackup'.\DIRECTORY_SEPARATOR.'DatabaseBackup.php';

return $this->privates['App\\Model\\DatabaseBackup\\DatabaseBackup'] = new \App\Model\DatabaseBackup\DatabaseBackup();
