<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MlGFGQs' shared service.

return $this->privates['.service_locator.MlGFGQs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authUtils' => ['services', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService.php', true],
    'visitorLog' => ['privates', 'App\\Model\\VisitorLog', 'getVisitorLogService.php', true],
], [
    'authUtils' => '?',
    'visitorLog' => 'App\\Model\\VisitorLog',
]);
