<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2uS1UwZ' shared service.

return $this->privates['.service_locator.2uS1UwZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'visitorLog' => ['privates', 'App\\Model\\VisitorLog', 'getVisitorLogService.php', true],
], [
    'encoder' => '?',
    'visitorLog' => 'App\\Model\\VisitorLog',
]);
