<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easy_deploy.command.rollback' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'easycorp'.\DIRECTORY_SEPARATOR.'easy-deploy-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'RollbackCommand.php';

$this->privates['easy_deploy.command.rollback'] = $instance = new \EasyCorp\Bundle\EasyDeployBundle\Command\RollbackCommand((($this->hasParameter("kernel.project_dir")) ? ($this->getParameter("kernel.project_dir")) : (($this->getParameter("kernel.root_dir") . "/.."))), (\dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'log'));

$instance->setName('rollback');

return $instance;
