<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AccessController:index' => function () {
    return ($this->privates['service_locator.XCGoua0'] ?? $this->load(__DIR__.'/getServiceLocator_XCGoua0Service.php'));
}, 'App\\Controller\\AccessController:register' => function () {
    return ($this->privates['service_locator.4C9qqux'] ?? $this->load(__DIR__.'/getServiceLocator_4C9qquxService.php'));
}, 'App\\Controller\\AccessController:reset_password' => function () {
    return ($this->privates['service_locator.L9RVTY8'] ?? $this->load(__DIR__.'/getServiceLocator_L9RVTY8Service.php'));
}, 'App\\Controller\\AccessController:reset_password2' => function () {
    return ($this->privates['service_locator.4C9qqux'] ?? $this->load(__DIR__.'/getServiceLocator_4C9qquxService.php'));
}, 'App\\Controller\\AccessController:verify_mda' => function () {
    return ($this->privates['service_locator.L9RVTY8'] ?? $this->load(__DIR__.'/getServiceLocator_L9RVTY8Service.php'));
}, 'App\\Controller\\AdminController:add_mda' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController:admin_update_password' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController:admin_users' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController:backup' => function () {
    return ($this->privates['service_locator.ZZ.P499'] ?? $this->load(__DIR__.'/getServiceLocator_ZZ_P499Service.php'));
}, 'App\\Controller\\AdminController:edit_mda' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\PagesController:generate_letter' => function () {
    return ($this->privates['service_locator.HHyOujQ'] ?? $this->load(__DIR__.'/getServiceLocator_HHyOujQService.php'));
}, 'App\\Controller\\PagesController:index' => function () {
    return ($this->privates['service_locator.r4SXgOy'] ?? $this->load(__DIR__.'/getServiceLocator_R4SXgOyService.php'));
}, 'App\\Controller\\PagesController:mda_2letter' => function () {
    return ($this->privates['service_locator.HcMlWfc'] ?? $this->load(__DIR__.'/getServiceLocator_HcMlWfcService.php'));
}, 'App\\Controller\\PagesController:mda_letter' => function () {
    return ($this->privates['service_locator.HcMlWfc'] ?? $this->load(__DIR__.'/getServiceLocator_HcMlWfcService.php'));
}, 'App\\Controller\\PagesController:print_mda_letter' => function () {
    return ($this->privates['service_locator.HcMlWfc'] ?? $this->load(__DIR__.'/getServiceLocator_HcMlWfcService.php'));
}, 'App\\Controller\\UserController:update_password' => function () {
    return ($this->privates['service_locator.IwzJ4c9'] ?? $this->load(__DIR__.'/getServiceLocator_IwzJ4c9Service.php'));
}, 'App\\Controller\\AccessController::index' => function () {
    return ($this->privates['service_locator.XCGoua0'] ?? $this->load(__DIR__.'/getServiceLocator_XCGoua0Service.php'));
}, 'App\\Controller\\AccessController::register' => function () {
    return ($this->privates['service_locator.4C9qqux'] ?? $this->load(__DIR__.'/getServiceLocator_4C9qquxService.php'));
}, 'App\\Controller\\AccessController::reset_password' => function () {
    return ($this->privates['service_locator.L9RVTY8'] ?? $this->load(__DIR__.'/getServiceLocator_L9RVTY8Service.php'));
}, 'App\\Controller\\AccessController::reset_password2' => function () {
    return ($this->privates['service_locator.4C9qqux'] ?? $this->load(__DIR__.'/getServiceLocator_4C9qquxService.php'));
}, 'App\\Controller\\AccessController::verify_mda' => function () {
    return ($this->privates['service_locator.L9RVTY8'] ?? $this->load(__DIR__.'/getServiceLocator_L9RVTY8Service.php'));
}, 'App\\Controller\\AdminController::add_mda' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController::admin_update_password' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController::admin_users' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\AdminController::backup' => function () {
    return ($this->privates['service_locator.ZZ.P499'] ?? $this->load(__DIR__.'/getServiceLocator_ZZ_P499Service.php'));
}, 'App\\Controller\\AdminController::edit_mda' => function () {
    return ($this->privates['service_locator.khmjDFP'] ?? $this->load(__DIR__.'/getServiceLocator_KhmjDFPService.php'));
}, 'App\\Controller\\PagesController::generate_letter' => function () {
    return ($this->privates['service_locator.HHyOujQ'] ?? $this->load(__DIR__.'/getServiceLocator_HHyOujQService.php'));
}, 'App\\Controller\\PagesController::index' => function () {
    return ($this->privates['service_locator.r4SXgOy'] ?? $this->load(__DIR__.'/getServiceLocator_R4SXgOyService.php'));
}, 'App\\Controller\\PagesController::mda_2letter' => function () {
    return ($this->privates['service_locator.HcMlWfc'] ?? $this->load(__DIR__.'/getServiceLocator_HcMlWfcService.php'));
}, 'App\\Controller\\PagesController::mda_letter' => function () {
    return ($this->privates['service_locator.HcMlWfc'] ?? $this->load(__DIR__.'/getServiceLocator_HcMlWfcService.php'));
}, 'App\\Controller\\PagesController::print_mda_letter' => function () {
    return ($this->privates['service_locator.HcMlWfc'] ?? $this->load(__DIR__.'/getServiceLocator_HcMlWfcService.php'));
}, 'App\\Controller\\UserController::update_password' => function () {
    return ($this->privates['service_locator.IwzJ4c9'] ?? $this->load(__DIR__.'/getServiceLocator_IwzJ4c9Service.php'));
})));
