<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Model\DatabaseBackup\DatabaseBackup' shared autowired service.

include_once $this->targetDirs[3].'/src/Model/DatabaseBackup/DatabaseBackup.php';

return $this->privates['App\Model\DatabaseBackup\DatabaseBackup'] = new \App\Model\DatabaseBackup\DatabaseBackup();
