<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ZZ.P499' shared service.

return $this->privates['service_locator.ZZ.P499'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('databaseBackup' => function (): ?\App\Model\DatabaseBackup\DatabaseBackup {
    return ($this->privates['App\Model\DatabaseBackup\DatabaseBackup'] ?? $this->privates['App\Model\DatabaseBackup\DatabaseBackup'] = new \App\Model\DatabaseBackup\DatabaseBackup());
}));
