<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.HHyOujQ' shared service.

return $this->privates['service_locator.HHyOujQ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('visitorLog' => function (): ?\App\Model\VisitorLog {
    return ($this->privates['App\Model\VisitorLog'] ?? $this->load(__DIR__.'/getVisitorLogService.php'));
}));
