<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Model\VisitorLog' shared autowired service.

include_once $this->targetDirs[3].'/src/Model/VisitorLog.php';

return $this->privates['App\Model\VisitorLog'] = new \App\Model\VisitorLog(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')));
