<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8YGqayl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8YGqayl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8YGqayl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8YGqayl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8YGqayl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8YGqayl',
    'container.build_id' => 'aa63ec03',
    'container.build_time' => 1753375505,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8YGqayl');
